### ISSUE TITLE
Suggestions s in Prog. Lang. Implementation Article

### ISSUE THREAD

**Issue by nobozo** [bread-man/mango#2]
(I tried emailing this to nevetia.vedant@gmail.com but it bounced).

1) "If my attempt at explaining to concept" ->
"If my attempt at explaining a concept"

2) "On Linux, considering apt is your package manager" ->
"On Linux, assuming apt is your package manager"

3) "Its a bunch of" ->
"It's a bunch of"

4) The "What is a Programming Language" section confuses
compilers and interpreters.

5) "procedural programming langauges are based on on method calls" ->
"procedural programming languages are based on method calls"

6) "Its made programatically" ->
"It's made programatically"

7) "namely whether its a keyword" ->
"namely whether it's a keyword"

8) many other "its" vs. "it's" errors.

**Comment by bread-man** [comment]
Thanks for this! I wrote it as kind of a first draft and might have overlooked these. I will fix them asap.
